name: Main

on:
  push:
    branches:
      - "*"
  delete:
    branches:
      - "*"

jobs:
  nothing:
    runs-on: ubuntu-latest
    steps:
      - run: echo 'ok'

  nothing-error:
    runs-on: ubuntu-latest
    steps:
      - run: echook
        
